namespace Takeaway_OS.API.DTOs;

public class CategoryDto  // shape returned by GET requests
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty; //name is never null
    public int DisplayOrder { get; set; }
}

public class CategoryCreateDto  // shape accepted by POST requests
{
    public string Name { get; set; } = string.Empty;
    public int DisplayOrder { get; set; }
}

public class CategoryUpdateDto // shape accepted by PUT requests
{
    public string Name { get; set; } = string.Empty;
    public int DisplayOrder { get; set; }
}

// no Id in the create and update DTOs because 
// the Id is generated by the database and should not be provided by the client.